name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set up permissions client
        run: chmod +x ./src/AndroidClient/gradlew

      - name: Build client
        working-directory: ./src/AndroidClient
        run: ./gradlew client:build

      - name: Build and Publish Client
        env:
          USERNAME_GITHUB: ${{ github.actor }}
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
          VERSION_SUFFIX: ${{ github.run_number }}
        working-directory: ./src/AndroidClient
        run: ./gradlew client:publishAllPublicationsToGitHubPackagesRepository -PversionSuffix=$VERSION_SUFFIX

      - name: Build android
        working-directory: ./src/AndroidClient
        run: ./gradlew android:build

      - name: Build and Publish Android
        env:
          USERNAME_GITHUB: ${{ github.actor }}
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
          VERSION_SUFFIX: ${{ github.run_number }}
        working-directory: ./src/AndroidClient
        run: ./gradlew android:publishAllPublicationsToGitHubPackagesRepository -PversionSuffix=$VERSION_SUFFIX

#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
