name: Stage android to Maven Central
# This workflow only Stages the package. You must manually login to https://oss.sonatype.org and publish from the Staging
# Repository. Recent outputs from this workflow will be listed there.
# You must "Close" each opened staging repository, then "Release". Closing can take some time, as can releasing.
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set up permissions client
        run: chmod +x ./src/AndroidClient/gradlew

      - name: Build android
        working-directory: ./src/AndroidClient
        run: ./gradlew android:build

      - name: Publish to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        working-directory: ./src/AndroidClient
        run: ./gradlew android:publishAllPublicationsToOSSRHRepository
