name: Publish to OSSRH

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Set up permissions client
        run: chmod +x ./src/AndroidClient/client/gradlew

      - name: Build client
        run: ./src/AndroidClient/client/gradlew build

      - name: Build and Publish
        env:
          USERNAME_GITHUB: ${{ github.actor }}
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        run: ./src/AndroidClient/client/gradlew publish

      - name: Set up permissions android
        run: chmod +x ./src/AndroidClient/android/gradlew

      - name: Build android
        run: ./src/AndroidClient/android/gradlew build

      - name: Build and Publish
        env:
          USERNAME_GITHUB: ${{ github.actor }}
          TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        run: ./src/AndroidClient/android/gradlew publish

#        env:
#          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
